### PR TITLE
Fix possible infinite loop when calculating amtEach

### PR DESCRIPTION
**Pull request by ultragtx**

### CODE REVIEW

**Comment by BeastOfBodmin** [comment]
I had this problem up until 1.08

My implementation of PHP causes `TenMinuteCron.php` to crap out after 30 seconds. I kept increasing the timeout, to no avail. In desperation, I started to dig into the code. ;-)

The net result was I wasn't getting funds lent out.

A friend did not have this problem. So I assumed it could have been something to do with my local setup, and so I did not raise a bug report.

It looks like `$numSplits = $this->actSettings['spreadlend'][$cur];` evaluates to zero sometimes. Consequently `$amtEach` barfs because of a divide by zero error.

My workaround was to put

```php
if($numSplits > 0) {

...

}
```

in here

```php
                        // is there anything left after the highhold?  if so, lets split it up //
                        if( $splitAvailable >= $minForLend ){
                                // How many splits do we want?
                                // gotta make sure each split is bigger than the minimum loan of $50 USD equiv
                                $numSplits = $this->actSettings['spreadlend'][$cur];

if($numSplits > 0) {

                                $amtEach = floor(($splitAvailable / $numSplits)*100)/100;
                                if($numSplits == 1){
                                        $amtEach = $splitAvailable;
                                }
```

which stopped `TenMinuteCron.php` from timing out.

**Comment by HFenter** [comment]
Hmm... $numSplits shouldn't ever be zero if your options are set up correctly for each currency.  I guess it would be possible to set it to zero, but you would have to do it intentionally by setting "change lending options" -> "Spread Available Lends" to zero.  I uhh, guess I didn't expect people to set that to zero.  One maybe, but not zero....  Anyways this fix should work well, so I'm going to merge it.

**Comment by ultragtx** [comment]
I didn't set numSplits to zero, seems that in some situations `$amtEach = floor(($splitAvailable / $numSplits)*100)/100;` can make $amtEach < $minForLend <= $splitAvailable

**Comment by HFenter** [comment]
Ah, yeah, running through the code again, I do see how that could happen.  Hmm.. there's probably a better way to do some of that whole loop, I may revisit in the next build (that code is actually a bit of a mess).  This fix should work for everyone having the issue until I improve that loop though.

**Pull request merged**
